stages:
  - build
  - deploy

variables:
  DOCKER_HUB_IMAGE: maksoncheus/taskmaster:2.0

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - docker build -t $DOCKER_HUB_IMAGE ./todo_project
    - docker push $DOCKER_HUB_IMAGE
  only:
    - main

deploy_to_prod:
  stage: deploy
  script:
    - echo "Deploying application..."
    - cd /home/maksim/my-djangooo/LAB3/
    - docker-compose down -v --remove-orphans
    - docker pull $DOCKER_HUB_IMAGE
    - docker-compose up -d
    - echo "Deployment finished!"
    - sleep 5
    - docker-compose ps
  tags:
    - deploy-makarov-vm
  only:
    - main
